### ISSUE TITLE
POLCA polishing

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#13]
New tool:
https://www.biorxiv.org/content/10.1101/2019.12.17.864991v1

tldr;
* same accuracy then pilon/racon
* ... but much faster

Idea: we could add a rule for POLCA and compare the outcome.

**Comment by sandraTriebel** [comment]
I didn't read the whole paper, but it look's nice.

But POLCA is part of the MaSuRCA genome assembly toolkit (https://github.com/alekseyzimin/masurca), which include an assembler too (we didn't include this assembler in the comparison in my bachelor thesis, because it would have been too much).
So it's possible, that POLCA might work better with this assembler than flye, isn't it?

POLCA only uses short reads for polishing a long-read assembly, so it could replace the 4 Racon runs w/ SR (1). Or should we polish the flye assembly with POLCA (2)?

(1) flye -> 4x Racon w/ LR -> 1x medaka w/ LR -> POLCA w/ SR (and compare these results with the current pipeline)
(2) flye -> POLCA w/ SR

**Comment by hoelzer** [comment]
Ah interesting that it is part of MaSuRCA. 

As far as I understood POLCA is for polishing an assembly using short reads, so I would say:

(1) flye -> 4x Racon w/ LR -> 1x medaka w/ LR -> POLCA w/ SR (and compare these results with the current pipeline)

would be the way to go.

**Comment by sandraTriebel** [comment]
We leaved POLCA out of the pipeline, because it would require a precise evaluation of the results. Moreover, POLCA is considered to use within the MaSuRCA pipeline.
